### ISSUE TITLE
Integration with signal-struct

### ISSUE THREAD

**Issue by dy** [WebReflection/signal#2]
Hey @WebReflection I attempted to integrate usignal and/or signal into [signal-struct](https://github.com/dy/signal-struct), and found out that doesn't play well, unlike @preact/signals-core. Would you be open to in looking at possible obstacles? I suspect that can be due to conscious limitations, just curious to know if you'd be interested.

**Comment by WebReflection** [comment]
Not interested for signal, possibly interested for usignal. Signal is a bare implementation playground, not planning to make it any more complex than it is now
